### ISSUE TITLE
the package.swift in subfolder can trigger a lot of events

### ISSUE THREAD

**Issue by aelam** [swift-server/vscode-swift#373] opened 2022-07-25 15:05 UTC
**Describe the bug**

My test case is the workspace folder doesn't have a Package.swift but subfolders have Package.swift in each of them.
when I tap one folder, the watcher starts to work

https://github.com/aelam/vscode-swift-test-packages/tree/main/

**To Reproduce**

**Expected behavior**

Only Package.swift in Root folder can trigger events? not sure current behavior is the expected one?

**Environment**
 - OS: [e.g. Ubuntu 20.04]
 - Swift version (output of `swift --version`)
 - Visual Studio Code version: 
 - vscode-swift version: 0.7.0

**Additional context**

**Comment by adam-fowler** [comment] 2022-07-26 10:22
Current behaviour is Package.swift files in subfolders (note, not when they are subfolders of a SwiftPM project), will be treated as swift projects, when you open files in them. This is the intended behaviour

**Comment by aelam** [comment] 2022-07-26 10:26
does it mean the .build folder will be generated.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by adam-fowler** [comment] 2022-07-26 10:27
It will run a `swift package resolve` on the project so yes.

**Comment by aelam** [comment] 2022-07-26 10:35
sorry my question is not clear enough

the folder structure like this
- Root
   - A/B/C
   - D

* A B C D are packages and they are under the same folder
* B C are the depencies of A
* open the folder by vscode

if I open C, does it mean C will be revolved?


follow-up question, how does the dependence lost show


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by adam-fowler** [comment] 2022-07-26 10:47
yes it will resolve C. The extension supports SwiftPM projects inside sub-folders as they may be part of a bigger project which involves multiple languages or they may be part of a suite of projects like a collection of lambdas. Also by resolving C you do get the advantage that it will allow you to run tests from C. 

It does not parse the folder structure in advance to find the SwiftPM projects as this may be an expensive operation based on how many subfolder projects there are. So each subfolder project is treated independently.

> how does the dependence lost show

Not sure what you mean

**Comment by aelam** [comment] 2022-07-26 10:59
I got your idea

>> how does the dependence list show

> Not sure what you mean

if I tap C/package.swift, will the dependency tree for C shown in VSCode?

**Comment by adam-fowler** [comment] 2022-07-26 11:00
> if I tap C/package.swift, will the dependency tree for C shown in VSCode?
yes

**Comment by aelam** [comment] 2022-07-26 11:07
is there a case that 
1. I modify A/Package.swift 
2. I modified B/Package.swift
3. currently, I'm on B
4. B responded faster than A
5. the final dependency list will be for A?

**Comment by adam-fowler** [comment] 2022-07-26 15:13
The dependency list is based on the currently viewed file

**Closed** 2022-07-30 11:53 UTC
Labels: bug
