### ISSUE TITLE
Support jump to test "always"

### ISSUE THREAD

**Issue by compnerd** [swift-server/vscode-swift#639] opened 2023-11-20 19:41 UTC
**Is your feature request related to a problem? Please describe.**
The jump to test is very convenient. However, it only appears when the file is open. However, often times, when debugging the test suite, it is that you hit the test without having touched it and the source file is not open. It would be nice to have the jump to test in those scenarios as well that would open and jump to the correct location.

**Describe the solution you'd like**
When the test suite is run (or even better when it is built), we have jump to test definition to quickly jump to the test definition even when the test source file is not open.

**Describe alternatives you've considered**
Opening all the test sources immediately, but this quickly becomes intractable when you have 100s of files with the tests.

**Additional context**

**Comment by adam-fowler** [comment] 2023-11-20 22:27
This is a duplicate of #192

**Closed** 2023-11-21 17:54 UTC
Labels: enhancement
