### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by filip-sakel** [swift-server/vscode-swift#326] opened 2022-06-09 13:25 UTC
**Is your feature request related to a problem? Please describe.**
Running plugins isn't supported within VS Code. But when using the command line to do so, the project builds separately. Additionally, testing invoked by the plugin doesn't show up in the VS Code UI.

**Describe the solution you'd like**
I'd like an easily discoverable interface for running command plugins, that allows for diagnostics, testing, and overall building the project from the plugin within the VS Code UI.

**Describe alternatives you've considered**
The swift extension and `swift build` (when run on the terminal) could use the same build folder to allow building once. This approach, however, doesn't take advantage of powerful plugin APIs that should integrate with the IDE/code editor.

**Comment by adam-fowler** [comment] 2022-06-09 13:39
Is this a duplicate of #292?

**Closed** 2022-06-09 16:04 UTC
Labels: enhancement

**Comment by adam-fowler** [comment] 2022-06-09 16:51
@filip-sakel Where is the Xcode command plugin selection interface?

**Comment by filip-sakel** [comment] 2022-06-09 21:44
It was shown at the WWDC [Platforms State of the Union](https://developer.apple.com/videos/play/wwdc2022/102/) at the 15:50 mark.

**Comment by adam-fowler** [comment] 2022-06-10 17:16
OK, I see it. #292 is about adding an interface (whether it be like Xcode or another design).
Related to your other points you made VSCode and `swift build` do use the same build folder. The VSCode tasks are just wrapped versions of `swift build`. So rebuilding shouldn't occur, unless you have different arguments for the two different builds.

> I'd like an easily discoverable interface for running command plugins, that allows for diagnostics, testing, and overall building the project from the plugin within the VS Code UI.

When you say testing are you talking about testing the plugin? Also what do you mean by overall building the project. Command plugins are meant to be run separate from the build process.
