### ISSUE TITLE
Cannot build Objective-C module

### ISSUE THREAD

**Issue by brucemontegani** [swift-server/vscode-swift#138] opened 2022-02-16 01:09 UTC
This may be more of a SourceKit-LSP issue but I keep getting an error when trying to import the XCTVapor module  
into a Test file

I get a red swingle under the X in XCTVapor and when I hover over it I get the following message:
"could not build Objective-C module 'XCTVapor'. sourcekitd"

I don't think this is an Objective C module.

I also get the same message in a Hummingbird project when trying to import the HummingbirdXCT module into a Test file.

**Comment by adam-fowler** [comment] 2022-02-16 08:05
Hi @brucemontegani this is an error returned by SourceKit-LSP. It seems to appear whenever you open a project which hasn't been built. If you build the project Cmd+Shift+B and select `Build All`. The error should go away. If it doesn't you might have to restart the LSP server. The easiest way to do this is bring up the command palette (Cmd+Shift+P) and select `Developer: Reload Window`.

**Comment by adam-fowler** [comment] 2022-02-16 14:24
https://forums.swift.org/t/unhelpful-error-could-not-build-objective-c-module-modulename/55381

**Comment by markst** [comment] 2022-06-05 22:18
Initially import fails with the following error:

> could not build Objective-C module 'Inject'sourcekitd

If running `swift build` in the root project:

> module 'Inject' was created for incompatible target arm64-apple-macosx10.15: /.build/arm64-apple-macosx/debug/Inject.swiftmodules

If running `swift build` with the following arguments:

```
swift build \
    --target Inject \
    --arch arm64 \
    -Xswiftc -sdk \
    -Xswiftc /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk \
    -Xswiftc -target \
    -Xswiftc arm64-apple-ios14.0-simulator
```

The import is satisfied after reloading the window.

**Comment by markst** [comment] 2022-06-05 22:26
Would it make sense to build dependencies an option as part of `resolveDependencies`?

**Comment by markst** [comment] 2022-06-05 22:57
Though maybe this is out of scope of what this extension is trying achieve. I can just create my own task to achieve this.

**Comment by ahoppen** [comment] 2023-06-27 10:51
I just hit this as well, investigated and understand what’s going wrong here. 

If you build a Swift package using `swift build`, the first thing that SwiftPM does is to create module map files. You can reproduce this by creating a new macro template, running Swift build and cancelling the build directly after the first files start compiling. In the debug folder you can see something like the following

```
arm64-apple-macosx/debug/SwiftCompilerPlugin.build
arm64-apple-macosx/debug/SwiftCompilerPlugin.build/sources
arm64-apple-macosx/debug/SwiftCompilerPlugin.build/output-file-map.json
arm64-apple-macosx/debug/SwiftCompilerPlugin.build/module.modulemap
```

With the module.modulemap contents as follows:

```
module SwiftCompilerPlugin {
    header "/private/tmp/MyMacro/.build/arm64-apple-macosx/debug/SwiftCompilerPlugin.build/SwiftCompilerPlugin-Swift.h"
    requires objc
}
```

If you use sourcekitd to get diagnostic at this stage, it finds the module map (aka. Objective-C module) and because SwiftCompilerPlugin-Swift.h doesn’t exist (yet), the diagnostic `could not build Objective-C module 'SwiftCompilerPlugin'` is technically correct. 

Now, as the build continues and the SwiftCompilerPlugin module gets compiled, the header file starts appearing and, more importantly, we get a `SwiftCompilerPlugin.swiftmodule`, which will get used instead of the modulemap.

---

So the issue here is because the `.modulemap` file is created significantly before the `.swiftmodule` file during a normal build. If we didn’t create the `.modulemap` file, you would get the following error message, which makes a lot more sense: `no such module 'SwiftCompilerPlugin'`

**Comment by ahoppen** [comment] 2023-06-27 10:55
I filed https://github.com/apple/swift-package-manager/issues/6671 to see if we can fix this in SwiftPM.

**Comment by ahoppen** [comment] 2024-04-12 21:58
I think this should be fixed with https://github.com/apple/swift-package-manager/issues/6671 being fixed.

**Closed** 2024-04-13 12:42 UTC
Labels: bug, sourcekit-lsp
