### ISSUE TITLE
[sourcekitd] false report "could not build Objective-C module 'foo'" on clean state

### ISSUE THREAD

**Issue by ljhm** [swift-server/vscode-swift#534] opened 2023-04-30 17:54 UTC
![Screen Shot 2023-05-01 at 1 52 30 AM](https://user-images.githubusercontent.com/9011764/235368557-24688583-fdd6-4d94-a005-c8d16075d78c.png)

1. $ swift package clean
 
2. Close and re-open vscode

After the status bar finishes showing:
    "Loading..", "Resolving..", "Activating.."

The “PROBLEMS” pane shows a false error message on clean state:
    "message": "could not build Objective-C module 'foo'",
    "source": "sourcekitd",

On source line like this:
import foo

foo is a standalone swift package with its own package.swift.
It’s of course outside the current importing projct directory.

3. swift build
4. Close and re-open vscode
5. The error message is gone. So, it occurs in clean state only.

* OS: macOS 12.6.5 (21G531)
* Swift version (swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51) Target: x86_64-apple-macosx12.0)
* Visual Studio Code version: Version: 1.77.3 (Universal)
* vscode-swift version: v1.2.1

**Comment by adam-fowler** [comment] 2023-04-30 20:55
Duplicate of #138

**Closed** 2023-04-30 20:55 UTC
Labels: bug, duplicate
