### ISSUE TITLE
Running a test spins for 15 seconds before triggering the build

### ISSUE THREAD

**Issue by tristanlabelle** [swift-server/vscode-swift#620] opened 2023-10-10 11:33 UTC
**Describe the bug**
When running a test from the test pane, VS Code does nothing for 15 seconds before triggering the build and running the test. I suspect it is detecting default build tasks?

![test-run-delay](https://github.com/swift-server/vscode-swift/assets/2314287/df042163-2aff-43dd-b238-78d55096aafe)

**To Reproduce**
In the test pane, click to run a test, then click to run it again (the second time should ensure a no-op build). Observe that the test timer starts and runs to about 15 seconds before a build is triggered and the test runs.

I was using https://github.com/tristanlabelle/swift-dotnetmetadata (Windows only), but I don't think it depends on this project. The project has no `tasks.json`, so this may be an issue of default build task discovery performance.

**Expected behavior**

**Environment**
 - OS: Windows 11
 - Swift version:
 ```
compnerd.org Swift version 5.9-dev (LLVM fd38736063c15cd, Swift a533c63d783f5b8)
Target: x86_64-unknown-windows-msvc
AKA 0.0.0-DEVELOPMENT-SNAPSHOT-2023-08-12-a
```
 - Visual Studio Code version: 1.83
 - vscode-swift version: v1.5.2

**Comment by adam-fowler** [comment] 2023-11-01 17:50
I wonder if this is related to #625 where the environment variables for the shell used to build the project, change with each run. 
See also https://forums.swift.org/t/rebuild-times-in-new-shell-significantly-slower/68054

**Comment by tristanlabelle** [comment] 2023-11-08 19:50
That's very possible! I'll verify with the newer toolchain when I get a chance, since this was fixed. Feel free to dupe this issue in the meantime.

**Comment by adam-fowler** [comment] 2024-02-16 12:36
Duplicate of #625

**Closed by adam-fowler** 2024-02-16 12:36 UTC
Labels: bug, waiting on input, windows
