### ISSUE TITLE
Quirks surrounding inlay hints

### ISSUE THREAD

**Issue by tinder-tannerbennett** [swift-server/vscode-swift#554] opened 2023-06-14 21:39 UTC
Inlay hints provided by this extension pose a couple of issues.

1. First, hints for tuple payload types look strange; the types are surrounded with parenthesis, like this:

    <img width="450" alt="Screenshot 2023-06-13 at 4 54 23 PM" src="https://github.com/microsoft/vscode-discussions/assets/89099176/d7fbf8f8-327d-476f-8280-9841b7378f72">

2. Second, you can double click to insert these hints, and they are not all valid syntax.

Regarding the first one, I suppose SourceKit-LSP is giving us back bad data. I can open an issue on that repo if someone here can confirm that is a change Apple needs to make.

As for the second issue, I believe it [may be possible to disable interacting with certain hints](https://github.com/swift-server/vscode-swift/issues/422#issuecomment-1592018033_) (via the [`vscode` headers](https://github.com/microsoft/vscode/blob/e3f0f4a875e5a24cdfd3d0c457835670e39569ee/src/vscode-dts/vscode.d.ts#L5117-L5127)), or at the very least, disable inserting any of the hints at all. Best case scenario, we can make it so that double clicking on "partially valid" hints—such as type labels for closure arguments—inserts the required parenthesis surrounding the parameters, as well as the selected type, and disable interacting with tuple payload hints entirely.

I am happy to help with this if this is something you want to move forward with!

**Comment by adam-fowler** [comment] 2023-06-15 08:04
Both of these would be resolved from changes to sourcekit-lsp. The textEdits field is returned from sourcekit-lsp as part of the InlayHint. If you set the sourcekit-lsp:trace.server option to verbose you can view all the communication with the sourcekit-lsp server via the sourcekit-lsp output pane. 

I guess in theory a language client middleware could be written to catch inlay hints and remove the textEdits field but there would be no easy way to recognise which inlay hints should have their textEdits removed. So it would most likely remove all or none.

**Comment by adam-fowler** [comment] 2023-06-15 08:07
@fwcd given you wrote the SourceKit-LSP InlayHint implementation do you have any ideas how we may go about recognising InlayHints that shouldn't provide test edits?

**Comment by NSExceptional** [comment] 2023-06-15 17:05
> I guess in theory a language client middleware could be written to catch inlay hints and remove the textEdits field but there would be no easy way to recognise which inlay hints should have their textEdits removed. So it would most likely remove all or none.

Sounds like the change needs to happen entirely on the SourceKit side then!

**Comment by fwcd** [comment] 2023-06-15 20:42
Yeah the tuple quirk is something I've noticed too, that needs to be fixed in SourceKit, possibly even somewhere deeper in the compiler. Hovers have the same issue IIRC.

As for the invalid syntax, adding parentheses on unparenthesized closure parameters as edits sounds absolutely reasonable. This is probably primarily something for SourceKit-LSP, but might require updates on the SourceKit-side too, given that the `CollectVariableType` request doesn't expose any higher-level semantic information about the kind of variable (if I remember correctly, it's been a while).

If nothing else, disabling the 'click-to-accept' would be a good idea. I am not quite sure how this is handled across LSP clients, e.g. whether VSCode interprets an empty array of edits as 'cannot accept' or whether the annotation itself has to be provided as an insert edit. In any case, that's most likely not something for the VSCode Swift extension to handle, given that inlay hints are LSP-native.

**Comment by fwcd** [comment] 2023-06-15 21:19
Yes, we should tackle the root cause on the server instead of patching around the issue on the client-side (which would be less accurate too, given that those hints don't have a lot of semantic info attached to them).

**Comment by adam-fowler** [comment] 2023-06-16 07:35
> I don't think you're forwarding text edits at all, at least that I could find. The default text edits just inserts the hint I believe, so if we aren't passing any text edits in, that would explain this behavior

Here is an example response I just took from the SourceKit-LSP output pane. You'll see there is a textEdit section there
```
[
    {
        "label": ": EventLoop",
        "kind": 1,
        "textEdits": [
            {
                "range": {
                    "start": {
                        "line": 44,
                        "character": 21
                    },
                    "end": {
                        "line": 44,
                        "character": 21
                    }
                },
                "newText": ": EventLoop"
            }
        ],
        "position": {
            "line": 44,
            "character": 21
        }
    },
```

**Comment by NSExceptional** [comment] 2023-06-16 17:56
Yes, but… are we returning that back to VS Code? This is the code I could find, and we're not giving back the text edits here:

https://github.com/swift-server/vscode-swift/blob/67c766d236ea138a2316334b6fb2be8969f9efaa/src/sourcekit-lsp/inlayHints.ts#L55-L60

Or is it happening somewhere else?

**Comment by adam-fowler** [comment] 2023-06-16 17:58
@NSExceptional that is the legacy code needed for InlayHints to work on Swift 5.6 and earlier. We updated Sourcekit-LSP in 5.7 to provide the official LSP spec when VSCode add support for it.

**Comment by NSExceptional** [comment] 2023-06-16 18:28
@fwcd That's SourceKit code though, where are _we_ passing _that_ to VS Code?

**Comment by fwcd** [comment] 2023-06-16 18:38
That happens in the `vscode-languageclient` lib

**Comment by adam-fowler** [comment] 2023-06-16 18:56
It one of the wonders of LSP 😃 . As long as SourceKit-LSP, advertises it supports a feature and provides the correct responses the vscode-swift extension doesn't need to do anything for feature to work.

**Comment by NSExceptional** [comment] 2023-06-16 19:23
Oh, gotcha 🥸 Thanks!

**Comment by adam-fowler** [comment] 2023-06-30 08:53
As a temporary measure I have added #560

**Comment by adam-fowler** [comment] 2023-06-30 09:33
Also added https://github.com/apple/sourcekit-lsp/issues/759

**Closed** 2023-07-09 14:47 UTC

**Comment by NSExceptional** [comment] 2023-07-14 23:41
Thank you @adam-fowler 🤘
