### ISSUE TITLE
No intellisense for types from other targets

### ISSUE THREAD

**Issue by GideonUng** [swift-server/vscode-swift#480] opened 2023-01-22 01:47 UTC
**Describe the bug**
no intellisense on windows when trying to use other targets.

**To Reproduce**
1) swift package init
2) add second target to package
3) add second target to first target as dep
4) rebuild
5) try using any types from second target

**Expected behavior**
auto completion & inley hints for deduced types

**Environment**
 - OS: Windows 11
 - Swift version: 5.7.3
 - Visual Studio Code version: 1.74.3
 - vscode-swift version: 1.0.0

**Comment by adam-fowler** [comment] 2023-01-22 17:34
The cause of this is the same issue as #479, so I'm going to close this

**Closed by adam-fowler** 2023-01-22 17:34 UTC
Labels: bug, duplicate

**Comment by GideonUng** [comment] 2023-01-22 19:32
I opened this since i dont think it is. The other issue is about files inside the same target, which has previously worked for me. this is about symbols coming from another target, which has never worked for me on windows.

**Comment by adam-fowler** [comment] 2023-01-22 19:51
Ok I'll reopen when we resolve the other issue and this is still a problem. If you saw my responses to the other issue you'll see frustratingly I can get it to work fine.

**Comment by GideonUng** [comment] 2023-01-22 19:58
I have had this same problem on 3 different machines and about 7 windows installs. So its very persistent and repeatable for me. 
I reinstall windows often and then see if this has been fixed for about a year now since id be quite interested in swift if i could work with it reliably on windows.
