### ISSUE TITLE
Notes that are attached to an error should be shown in the Problems View

### ISSUE THREAD

**Issue by ahoppen** [swift-server/vscode-swift#658] opened 2023-12-09 02:35 UTC
For example, when compiling 

```swift
func foo() {
  let x: Int
  print(x)
}
```

The compiler outputs the following diagnostics

```
/path/to/test.swift:3:9: error: constant 'x' used before being initialized
  print(x)
        ^
/path/to/test.swift:2:7: note: constant defined here
  let x: Int
      ^
```

VS Code should display these notes as children of the errors they are attached to in the Problems view. Currently, it shows them as standalone diagnostics that aren’t linked to their parent.

<img width="879" alt="Screenshot 2023-12-08 at 18 34 17" src="https://github.com/swift-server/vscode-swift/assets/4062178/61dab643-9a8c-4430-b9a5-a2000e5fdc6f">

**Comment by adam-fowler** [comment] 2023-12-09 07:45
This is duplicate of #570

**Closed by adam-fowler** 2023-12-09 07:45 UTC
