### ISSUE TITLE
Add rename refactorings

### ISSUE THREAD

**Issue by MartinLau7** [swift-server/vscode-swift#495] opened 2023-02-22 01:28 UTC
Rename refactoring allows you to rename symbols, files, and directories globally with all the references to them in the code corrected automatically.
I did not find support for this feature in the VSCode-swift extension

**Comment by adam-fowler** [comment] 2023-02-22 07:10
Duplicate of #415. Also this is really a SourceKit-LSP issue. You can see the relevant issue here https://github.com/apple/sourcekit-lsp/issues/498

**Closed by adam-fowler** 2023-02-22 07:10 UTC
Labels: duplicate, enhancement
