### ISSUE TITLE
Verify SSWG with Swift.org ownership?

### ISSUE THREAD

**Issue by stevapple** [swift-server/vscode-swift#226] opened 2022-04-04 14:36 UTC
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Can we verify SSWG with Swift.org, to mark this plugin as "official" in VS Marketplace?

**Describe alternatives you've considered**

Keep it as is now.

**Additional context**

https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

**Comment by adam-fowler** [comment] 2022-04-04 14:54
Duplicate of #86

**Comment by 0xTim** [comment] 2022-04-04 16:12
cc @tomerd

**Closed by 0xTim** 2022-04-04 16:12 UTC
Labels: enhancement
